- name: Henrik Linusson
  email: henrik@ekkono.ai
- name: Giovanni Cherubin
  email: giovanni.cherubin@gmail.com
- name: tuvelofstrom
  email: tuve.open@gmail.com
- name: Isak Karlsson
  email: isak.karlsson@gmail.com
- name: Zygmunt Zając
  email: zajac.zygmunt@gmail.com
- name: Martín Villanueva
  email: nallivam@gmail.com
